### ISSUE TITLE
Don't forget `TODO`in code

### ISSUE THREAD

**Issue by kiki-le-singe** [kiki-le-singe/the-kiki-s-social-network-api#6]
- [ ] [TODO - L16](https://github.com/kiki-le-singe/the-kiki-s-social-network-api/blob/master/config/index.js#L16)
- [x] [TODO - L69](https://github.com/kiki-le-singe/the-kiki-s-social-network-api/blob/master/routes/auth.js#L69)
- [ ] [TODO - L54](https://github.com/kiki-le-singe/the-kiki-s-social-network-api/blob/master/routes/auth.js#L54)
